# Generated by Django 3.1 on 2022-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
